On-fly-message-self: '&3Test message for fly ON self' #enter the fly command ON message ( for /fly only)
Off-fly-message-self: '&4Test message for fly off self' #enter the fly command OFF message(for /fly only)

On-fly-message-ingame-player: '&9test message for fly on player' #enter the fly command ON message (for /fly <playername> ingame only)
Off-fly-message-ingame-player: '&6test message for fly off player' #enter the fly command OFF message (for /fly <playername> ingame only)

On-fly-message-concole: 'test message for fly on console' #enther the fly command ON message while running it from console
Off-fly-message-concole: 'test message for fly off console' #enther the fly command OFF message while running it from console

No-player-found-message: 'test command for no player found' #enther the message, when player not found
# --- the color codes ---

#  Black (&0)
#  Dark Blue (&1)
#  Dark Green (&2)
#  Dark Aqua (&3)
#  Dark Red (&4)
#  Dark Purple (&5)
#  Gold (&6)
#  Gray (&7)
#  Dark Gray (&8)
#  Blue (&9)
#  Green (&a)
#  Aqua (&b)
#  Red (&c)
#  Light Purple (&d)
#  Yellow (&e)
#  White (&f)

# -- Formats --

#  Magic (&k)
#  Bold (&l)
#  Strike (&m)
#  Underline (&n)
#  Italic (&o)
#  Reset (&r)
